@startuml component

package "com.example.kitchen" {
    [KitchenApplication] --> [KitchenService]
    [KitchenService] --> [ClientCommandsHandler]
    [KitchenService] --> [RestaurantState]
    [KitchenService] --> [KitchenRequest]
    [ClientCommandsHandler] --> [ClientCommand]
}

@enduml